# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170106_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_notes',
            field=models.TextField(default=b''),
        ),
    ]
