# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patient_doctor_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnreadMessage',
        ),
        migrations.AddField(
            model_name='patient',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
    ]
