# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170123_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='twilio_token',
            field=models.TextField(default=b''),
        ),
    ]
