# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doctor_twilio_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ESASQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default=b'')),
                ('answer', models.TextField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='PainPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('intensity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PainSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='u_id',
            new_name='sid',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='u_id',
            new_name='sid',
        ),
        migrations.AddField(
            model_name='painsurvey',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
        ),
        migrations.AddField(
            model_name='painsurvey',
            name='points',
            field=models.ManyToManyField(to='app.PainPoint'),
        ),
        migrations.AddField(
            model_name='esas',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
        ),
        migrations.AddField(
            model_name='esas',
            name='questions',
            field=models.ManyToManyField(to='app.ESASQuestion'),
        ),
    ]
