# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170203_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esas',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='esas',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='painsurvey',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='painsurvey',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='esas',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='painsurvey',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
