# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170203_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esas',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
        ),
        migrations.AlterField(
            model_name='painsurvey',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
        ),
    ]
