# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170203_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ESAS',
            new_name='ESASSurvey',
        ),
        migrations.AlterField(
            model_name='esasquestion',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
