# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170203_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esassurvey',
            options={'ordering': ('-created_date',)},
        ),
    ]
