# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_patient_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='caregiver_name',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='city_of_residence',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_type',
            field=models.CharField(choices=[(b'Palliative Care Only', b'Palliative Care Only'), (b'Undergoing Anticancer Therapy', b'Undergoing Anticancer Therapy')], default=b'Palliative Care Only', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
