# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170217_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=255)),
                ('form', models.CharField(default=b'', max_length=255)),
                ('dose', models.CharField(default=b'', max_length=255)),
                ('posology', models.CharField(default=b'', max_length=255)),
                ('rescue', models.TextField(default=b'')),
            ],
        ),
    ]
