# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='next_appointment',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
