# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 18:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_patient_next_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
            preserve_default=False,
        ),
    ]
