# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170217_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[(b'Female', b'F'), (b'Male', b'M')], default=b'', max_length=255),
        ),
    ]
