# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[(b'F', b'Female'), (b'M', b'Male')], default=b'', max_length=255),
        ),
    ]
