# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170217_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[(b'Female', b'Female'), (b'Male', b'Male')], default=b'', max_length=255),
        ),
    ]
