# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20170217_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esassurvey',
            name='questions',
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='anxiety',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='appetite',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='depression',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='drowsiness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='fatigue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='insomnia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='lack_of_air',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='nausea',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='pain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='well_being',
            field=models.IntegerField(null=True),
        ),
    ]
