# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170218_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='esassurvey',
            name='confusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='constipation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='constipation_bothered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='constipation_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='vomiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='esassurvey',
            name='vomiting_count',
            field=models.IntegerField(default=0),
        ),
    ]
