# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20170219_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esassurvey',
            old_name='confusion',
            new_name='confused',
        ),
        migrations.RenameField(
            model_name='esassurvey',
            old_name='constipation',
            new_name='constipated',
        ),
        migrations.RenameField(
            model_name='esassurvey',
            old_name='constipation_bothered',
            new_name='constipated_bothered',
        ),
        migrations.RenameField(
            model_name='esassurvey',
            old_name='constipation_days',
            new_name='constipated_days',
        ),
    ]
