# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20170219_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esassurvey',
            name='confused',
            field=models.CharField(default=b'no', max_length=255),
        ),
        migrations.AlterField(
            model_name='esassurvey',
            name='constipated',
            field=models.CharField(default=b'no', max_length=255),
        ),
        migrations.AlterField(
            model_name='esassurvey',
            name='fever',
            field=models.CharField(default=b'no', max_length=255),
        ),
        migrations.AlterField(
            model_name='esassurvey',
            name='vomiting',
            field=models.CharField(default=b'no', max_length=255),
        ),
    ]
