# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170219_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.TextField(default=b'')),
                ('category', models.CharField(choices=[(b'ESAS', b'ESAS'), (b'Pain', b'Pain'), (b'Medication', b'Medication'), (b'Custom', b'Custom')], default=b'Custom', max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient')),
            ],
        ),
    ]
