# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 22:54
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20170221_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Patient')),
                ('file', models.FileField(upload_to=app.models.user_directory_path)),
            ],
        ),
    ]
