# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='patient',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
