# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 19:50
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(upload_to=app.models.user_directory_path)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='patient',
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_date',)},
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
