# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170223_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painsurvey',
            old_name='points',
            new_name='front_points',
        ),
    ]
