# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20170224_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='painsurvey',
            name='back_points',
            field=models.ManyToManyField(related_name='back_points', to='app.PainPoint'),
        ),
        migrations.AlterField(
            model_name='painsurvey',
            name='front_points',
            field=models.ManyToManyField(related_name='front_points', to='app.PainPoint'),
        ),
    ]
