# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20170224_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sid',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[(b'ESAS', b'ESAS'), (b'PAIN', b'Pain'), (b'MEDICATION', b'Medication'), (b'OTHER', b'Other')], default=b'OTHER', max_length=255),
        ),
    ]
