# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20170224_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='painpoint',
            name='rgb',
            field=models.IntegerField(default=216),
            preserve_default=False,
        ),
    ]
