# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_painpoint_rgb'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='esassurvey',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medication',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='painsurvey',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_appointment',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
