# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_dashboardalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardalert',
            name='patient',
        ),
        migrations.DeleteModel(
            name='DashboardAlert',
        ),
    ]
