# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_dashboardalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='MedicationReportEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='medicationreportentry',
            name='statuses',
            field=models.ManyToManyField(related_name='statuses', to='app.MedicationStatus'),
        ),
        migrations.AddField(
            model_name='medicationreport',
            name='entries',
            field=models.ManyToManyField(related_name='entries', to='app.MedicationReportEntry'),
        ),
        migrations.AddField(
            model_name='medicationreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
        ),
    ]
