# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20170408_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationreportentry',
            name='name',
        ),
        migrations.AddField(
            model_name='medicationreportentry',
            name='medication',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.Medication'),
            preserve_default=False,
        ),
    ]
