# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20170408_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationstatus',
            options={'ordering': ('hour',)},
        ),
    ]
