# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20170408_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationstatus',
            name='completed',
            field=models.NullBooleanField(),
        ),
    ]
