# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 01:33
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20170408_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=b'', max_length=128),
        ),
    ]
