# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_doctor_telephone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationstatus',
            options={'ordering': ('time',)},
        ),
        migrations.RemoveField(
            model_name='medicationstatus',
            name='hour',
        ),
        migrations.AddField(
            model_name='medicationstatus',
            name='time',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
