# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20170410_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('front_blob_name', models.CharField(default=b'', max_length=255)),
                ('back_blob_name', models.CharField(default=b'', max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient')),
            ],
        ),
    ]
