# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_painimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='painimages',
            name='container_name',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
