# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20170411_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='esas_alert',
            field=models.IntegerField(default=7),
        ),
    ]
