# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20170423_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardalert',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AddField(
            model_name='dashboardalert',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
