# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20170424_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardalert',
            options={},
        ),
        migrations.RemoveField(
            model_name='dashboardalert',
            name='created_date',
        ),
    ]
