# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-17 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20170424_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='caregiver_relationships',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='comorbidities',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='tumor_type',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
