# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20170917_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='painimages',
            name='left_blob_name',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='painimages',
            name='right_blob_name',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
