# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20171010_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='posology',
            new_name='num_doses',
        ),
        migrations.AddField(
            model_name='medication',
            name='dose_time_1',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='medication',
            name='dose_time_2',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='medication',
            name='dose_time_3',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='medication',
            name='dose_time_4',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='medication',
            name='dose_time_5',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='medication',
            name='dose_time_6',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
