# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-12 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20180212_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='num_doses',
            field=models.IntegerField(),
        ),
    ]
