# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-05 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20180212_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='dose_time_1',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dose_time_2',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dose_time_3',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dose_time_4',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dose_time_5',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dose_time_6',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='num_doses',
        ),
        migrations.AddField(
            model_name='medication',
            name='posology',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
